import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

const resources = {
  en: {
    translation: {
      "welcome_title": "Spotlight: Your Musical Theatre Advisor",
      "welcome_subtitle": "Find the perfect musical for your night out in London",
      "start_fresh": "Start Fresh",
      "start_fresh_desc": "Get personalised show recommendations based on your preferences",
      "cant_decide": "Can't Decide",
      "cant_decide_desc": "Compare shows you're considering and get help choosing the right one",
      "browse_all": "Browse All Shows",
      "browse_all_desc": "Explore every show and filter by genre, vibe, and tags",
      "questions_v2": "Questions V2",
      "questions_v2_desc": "Try our updated recommendation quiz with enhanced questions",
      "about_app": "About This App",
      "back": "Back",
      "find_my_show": "Find My Show",
      "continue": "Continue",
      "footer_made_by": "Made by Tsuf Eden, a Theatre Lover",
      "footer_instagram": "tsufi on Instagram",
      "footer_tiktok": "Juicy Theatre on TikTok",
      "loading": "Loading...",
      "direction": "ltr",

      // Results & Recommendations
      "top_recommendation": "Top Recommendation",
      "with_interval": "with interval",
      "no_interval": "no interval",
      "about_show": "About",
      "tags": "Tags",
      "from_date": "From {{date}}",
      "why_we_recommend": "Why we recommend this",
      "matches_preferences": "Matches your overall preferences",
      "great_match": "Great match for what you're looking for",
      "get_tickets": "Get Tickets",
      "score_breakdown": "Score Breakdown",
      "filters_passed": "Filters Passed",
      "positive_contributions": "Positive Contributions",
      "negative_contributions": "Negative Contributions",
      "zero_impact": "Zero Impact",
      "total": "Total",

      // Quiz
      "select_one": "Select one",
      "select_multiple": "Select multiple options",
      "drag_to_reorder": "Drag to reorder",
      "tap_to_select": "Tap to select",
      "ranking_instruction": "Drag and drop to rank from most to least important",
      "arrival_date": "Arrival Date",
      "departure_date": "Departure Date",
      "date_error_order": "Start date must be before end date",

      // Common
      "no_results": "No results found",
      "try_adjusting": "Try adjusting your filters",
      "start_over": "Start Over",
      "no_perfect_match_title": "No Perfect Match Found",
      "no_perfect_match_desc": "We couldn't find a show that matches all your criteria. Try adjusting your preferences:",
      "retake_quiz": "Retake Quiz",

      // Browse
      "back_to_home": "Back to Home",
      "browse_all_subtitle": "Explore the full West End lineup",
      "search_placeholder": "Search by show title or description...",
      "quick_filters": "Quick Filters",
      "showing_results": "Showing {{count}} of {{total}} shows",
      "no_shows_match": "No shows match your filters",
      "clear_filters": "Clear Filters",
      "details": "Details",
      "tickets": "Tickets",

      // Show Selector
      "select_shows_to_compare": "Select Shows to Compare",
      "choose_2_to_4": "Choose 2 to 4 shows you're considering",
      "max_compare_error": "You can compare up to 4 shows.",
      "select_at_least_2": "Select at least 2 shows",
      "select_at_least_1_more": "Select at least 1 more show",
      "selected_count_more": "{{count}} selected • You can select {{remaining}} more",
      "max_selected": "4 shows selected (maximum)",

      // About Recommendation
      "about_recommendation_title": "About This Recommendation",
      "about_recommendation_p1": "My name is Tsuf Eden, I'm a theatre lover.",
      "about_recommendation_p2": "I watch all the musicals London has to offer and I love helping others make the most of their London trip through unforgettable theatre experiences.",
      "about_recommendation_p3": "My goal is to remove the stress of choosing a show. I combine insider knowledge, smart curation, and storytelling that actually helps you decide what feels right – not just what's popular.",
      "about_recommendation_p4": "Your recommendation is generated by AI that is guided and trained by my theatre experience, using your preferences to find the show that best fits your taste, energy, and the kind of night you want to have, so you can get guidance that feels like a friend who truly knows theatre.",
      "read_more": "Read more",
      "expand": "Expand",
      "collapse": "Collapse",

      // Home.jsx - Loading & Errors
      "loading_shows": "Loading shows...",
      "loading_v2": "Loading V2 questions...",
      "calculating_results": "Calculating your results...",
      "config_load_failed": "Config Load Failed",
      "go_back": "Go Back",
      "error_title": "Something went wrong calculating your results",
      "error_desc": "We couldn't complete your search. Please try again.",
      "refresh_suggestion": "If this keeps happening, try refreshing the page.",
      "try_again": "Try Again",
      "top_picks_title": "Here are my top picks for you",
      "start_over_fresh": "Start Over",
      "select_more_options": "You can select {{count}} more option{{plural}}",
      "max_selections_reached": "Maximum selections reached",
      "quiz_progress": "Question {{current}} of {{total}}",
      "sign_in_to_see_more": "Sign in to see {{count}} more personalised suggestions",
      "continue_with_google": "Continue with Google",
      "redirecting_to_google": "Redirecting to Google…",
      "sign_in_failed": "Sign-in failed. Please try again.",
      "date_range": "{{start}} – {{end}}",
      "opening_soon": "Opening soon",
      "closing_soon": "Closing soon",
      "loading_shows_browse": "Loading shows...",
      "clear_all_filters": "Clear All Filters",
      "filter_family_friendly": "Family Friendly",
      "filter_funny": "Funny",
      "filter_romantic": "Romantic",
      "filter_spectacle": "Big Spectacle",
      "filter_easy_english": "Easy English",
      "filter_must_see": "Must See",
      "filter_hidden_gem": "Hidden Gem",
      "filter_tsufs_faves": "Tsuf's Favourites",
      "filter_off_west_end": "Off West End",

      // Field Preferences
      "preference": {
        "darkness_level": {
          "positive": "a darker, more intense tone",
          "negative": "a lighter, more feel-good tone"
        },
        "jukebox": {
          "positive": "famous songs (jukebox-style music)",
          "negative": "original music (less jukebox-style)"
        },
        "music_familiarity": {
          "positive": "familiar, easy-to-enjoy music",
          "negative": "new and original music"
        },
        "spectacle_level": {
          "positive": "big spectacle and visual wow",
          "negative": "a more intimate, story-led show"
        },
        "comedy_score": {
          "positive": "comedy and laughs",
          "negative": "a more serious, emotional tone"
        },
        "family_score": {
          "positive": "a family-friendly show",
          "negative": "a more adult-focused show"
        },
        "family_friendly": {
          "positive": "a family-friendly show",
          "negative": "a more adult-focused show"
        },
        "beginner_friendly": {
          "positive": "easy to follow for first-timers",
          "negative": "better suited for experienced musical fans"
        },
        "emotional_intensity": {
          "positive": "strong emotional impact",
          "negative": "a lighter emotional experience"
        },
        "tone_match": {
          "positive": "a closer match to your preferred tone",
          "negative": "a different tone than what you prefer"
        },
        "energy_level": {
          "positive": "high energy",
          "negative": "a more relaxed pace"
        },
        "romance_score": {
          "positive": "romance and relationships",
          "negative": "less focus on romance"
        },
        "humor_level": {
          "positive": "comedy and laughs",
          "negative": "a more serious tone"
        },
        "music_quality": {
          "positive": "memorable music",
          "negative": "less focus on musical quality"
        },
        "story_depth": {
          "positive": "strong storytelling",
          "negative": "less focus on story depth"
        },
        "classic": {
          "positive": "a classic musical",
          "negative": "a more modern show"
        },
        "must_see": {
          "positive": "a must-see crowd-pleaser",
          "negative": "a less mainstream show"
        },
        "hidden_gem": {
          "positive": "something different and unique",
          "negative": "a more mainstream choice"
        }
      },

      // Comparisons
      "comparison": {
        "spectacle_level": {
          "0": "{{winner}} delivers more visual spectacle than {{loser}}",
          "1": "{{loser}} is more intimate in scale"
        },
        "humor_level": {
          "0": "{{winner}} is funnier than {{loser}}",
          "1": "{{loser}} takes itself more seriously"
        },
        "comedy_score": {
          "0": "{{winner}} leans more into comedy than {{loser}}",
          "1": "{{loser}} has less comedic moments"
        },
        "emotional_intensity": {
          "high_vs_low": {
            "0": "{{winner}} has more emotional depth than {{loser}}",
            "1": "{{loser}} is lighter in tone"
          },
          "low_vs_high": {
            "0": "{{winner}} is lighter than {{loser}}",
            "1": "{{loser}} is heavier and more intense"
          }
        },
        "energy_level": {
          "0": "{{winner}} matches your energy preference better than {{loser}}",
          "1": "{{loser}} has a different pace"
        },
        "beginner_friendly": {
          "0": "{{winner}} is more accessible for first-timers than {{loser}}",
          "1": "{{loser}} assumes more theatre experience"
        },
        "family_friendly": {
          "0": "{{winner}} is more suitable for kids than {{loser}}",
          "1": "{{loser}} is more adult-oriented"
        },
        "family_score": {
          "0": "{{winner}} works better for families than {{loser}}",
          "1": "{{loser}} is aimed at older audiences"
        },
        "jukebox": {
          "0": "{{winner}} features more familiar songs than {{loser}}",
          "1": "{{loser}} has more original music"
        },
        "music_familiarity": {
          "0": "{{winner}} is easier to enjoy musically than {{loser}}",
          "1": "{{loser}} has less familiar tunes"
        },
        "classic": {
          "0": "{{winner}} feels more like a classic musical than {{loser}}",
          "1": "{{loser}} is more modern in style"
        },
        "romance_score": {
          "0": "{{winner}} has more romance than {{loser}}",
          "1": "{{loser}} focuses less on relationships"
        },
        "default": {
          "0": "{{winner}} is stronger on this preference",
          "1": "{{loser}} doesn't match as closely"
        },

        // Reason fallbacks
        "date_mismatch": "The show is not running during your dates.",
        "kids_mismatch": "{{winner}} is more suitable for kids.",
        "duration_mismatch": "{{winner}} fits your preference for a shorter show better.",
        "english_mismatch": "{{winner}} is easier to follow with limited English.",
        "preference_match": "{{winner}} fits your preference for {{preference}} better than {{loser}}.",
        "overall_match": "{{winner}} is a stronger overall match for what you're looking for than {{loser}}.",
        "strong_on": "Strong on {{preference}}"
      }
    }
  },
  he: {
    translation: {
      "welcome_title": "Spotlight: יועץ התיאטרון המוזיקלי שלך",
      "welcome_subtitle": "מצאו את המחזמר המושלם לערב שלכם בלונדון",
      "start_fresh": "התחלה חדשה",
      "start_fresh_desc": "קבלו המלצות מותאמות אישית להצגות על בסיס ההעדפות שלכם",
      "cant_decide": "מתלבטים?",
      "cant_decide_desc": "השוו בין הצגות שאתם שוקלים וקבלו עזרה בבחירה הנכונה",
      "browse_all": "כל ההצגות",
      "browse_all_desc": "גלו את כל ההצגות וסננו לפי ז'אנר, אווירה ותגיות",
      "questions_v2": "שאלון V2",
      "questions_v2_desc": "נסו את השאלון המשודרג שלנו עם שאלות משופרות",
      "about_app": "אודות האפליקציה",
      "back": "חזור",
      "find_my_show": "סיום",
      "continue": "המשך",
      "footer_made_by": "נוצר ע\"י צוף אדן, חובבת תיאטרון",
      "footer_instagram": "tsufi באינסטגרם",
      "footer_tiktok": "Juicy Theatre בטיקטוק",
      "loading": "טוען...",
      "direction": "rtl",

      // Results & Recommendations
      "top_recommendation": "המלצה מובילה",
      "with_interval": "כולל הפסקה",
      "no_interval": "ללא הפסקה",
      "about_show": "אודות",
      "tags": "תגיות",
      "from_date": "החל מ-{{date}}",
      "why_we_recommend": "למה אנחנו ממליצים על זה",
      "matches_preferences": "מתאים להעדפות הכלליות שלך",
      "great_match": "התאמה מעולה למה שאתם מחפשים",
      "get_tickets": "רכישת כרטיסים",
      "score_breakdown": "פירוט הניקוד",
      "filters_passed": "סינונים שעברו",
      "positive_contributions": "השפעות חיוביות",
      "negative_contributions": "השפעות שליליות",
      "zero_impact": "ללא השפעה",
      "total": "סה\"כ",

      // Quiz
      "select_one": "בחרו אפשרות אחת",
      "select_multiple": "בחרו מספר אפשרויות",
      "drag_to_reorder": "גררו לשינוי הסדר",
      "tap_to_select": "לחצו לבחירה",
      "ranking_instruction": "גררו ושחררו כדי לדרג מהחשוב ביותר לפחות חשוב",
      "arrival_date": "תאריך הגעה",
      "departure_date": "תאריך עזיבה",
      "date_error_order": "תאריך ההתחלה חייב להיות לפני תאריך הסיום",

      // Common
      "no_results": "לא נמצאו תוצאות",
      "try_adjusting": "נסו לשנות את הסינונים",
      "start_over": "התחל מחדש",
      "no_perfect_match_title": "לא נמצאה התאמה מושלמת",
      "no_perfect_match_desc": "לא הצלחנו למצוא מופע שמתאים לכל הקריטריונים שלך. נסה להתאים את ההעדפות שלך:",
      "retake_quiz": "התחל מחדש",

      // Browse
      "back_to_home": "חזרה לדף הבית",
      "browse_all_subtitle": "גלו את כל ההצגות בלונדון",
      "search_placeholder": "חיפוש לפי שם ההצגה או תיאור...",
      "quick_filters": "סינון מהיר",
      "showing_results": "מציג {{count}} מתוך {{total}} הצגות",
      "no_shows_match": "לא נמצאו הצגות התואמות את הסינון",
      "clear_filters": "נקה סינונים",
      "details": "פרטים",
      "tickets": "כרטיסים",

      // Show Selector
      "select_shows_to_compare": "בחרו הצגות להשוואה",
      "choose_2_to_4": "בחרו 2 עד 4 הצגות שאתם שוקלים",
      "max_compare_error": "ניתן להשוות עד 4 הצגות.",
      "select_at_least_2": "בחרו לפחות 2 הצגות",
      "select_at_least_1_more": "בחרו לפחות עוד הצגה אחת",
      "selected_count_more": "{{count}} נבחרו • ניתן לבחור עוד {{remaining}}",
      "max_selected": "4 הצגות נבחרו (מקסימום)",

      // About Recommendation
      "about_recommendation_title": "אודות ההמלצה הזו",
      "about_recommendation_p1": "נעים להכיר, אני צוף אדן ואני חובבת תיאטרון מושבעת.",
      "about_recommendation_p2": "אחרי שראיתי את כל מחזות הזמר שיש ללונדון להציע, אני כאן כדי לעזור לכם להפוך את הטיול שלכם לבלתי נשכח עם בחירה מדוייקת של הצגה.",
      "about_recommendation_p3": "המטרה שלי היא להוריד מכם את הלחץ בבחירת ההצגה. בעזרת ידע מעמיק, המלצות מותאמות אישית, והבנה של החוויה הכוללת, אני אעזור לכם לבחור את מה שהכי נכון לכם – ולא רק את מה שכולם הולכים אליו.",
      "about_recommendation_p4": "ההמלצה שלכם נוצרת על ידי בינה מלאכותית המבוססת על הניסיון שלי בתיאטרון. היא משתמשת בהעדפות שלכם כדי למצוא את ההצגה שתתאים בול לטעם שלכם, לאנרגיה שאתם מחפשים ולסוג הערב שאתם רוצים לחוות – ממש כמו המלצה מחברה שמבינה עניין.",
      "read_more": "קרא עוד",
      "expand": "הרחב",
      "collapse": "צמצם",

      // Home.jsx - Loading & Errors
      "loading_shows": "טוען מופעים...",
      "loading_v2": "טוען שאלות...",
      "calculating_results": "מחשב את התוצאות שלך...",
      "config_load_failed": "טעינת הגדרות נכשלה",
      "go_back": "חזור",
      "error_title": "משהו השתבש בחישוב התוצאות שלך",
      "error_desc": "לא הצלחנו להשלים את החיפוש שלך. אנא נסה שוב.",
      "refresh_suggestion": "אם זה ממשיך לקרות, נסה לרענן את הדף.",
      "try_again": "נסה שוב",
      "top_picks_title": "הנה ההמלצות המובילות שלי בשבילך",
      "start_over_fresh": "התחל מחדש",
      "select_more_options": "ניתן לבחור עוד {{count}} אפשרויות",
      "max_selections_reached": "הגעת למקסימום הבחירות",
      "quiz_progress": "שאלה {{current}} מתוך {{total}}",
      "sign_in_to_see_more": "היכנסי כדי לראות עוד {{count}} המלצות מותאמות אישית",
      "continue_with_google": "המשך עם Google",
      "redirecting_to_google": "מועבר/ת לגוגל...",
      "sign_in_failed": "ההתחברות נכשלה. אנא נסי שוב.",
      "date_range": "{{start}} – {{end}}",
      "opening_soon": "בקרוב",
      "closing_soon": "נסגר בקרוב",
      "loading_shows_browse": "טוען הצגות...",
      "clear_all_filters": "נקה כל הסינונים",
      "filter_family_friendly": "ידידותי למשפחה",
      "filter_funny": "מצחיק",
      "filter_romantic": "רומנטי",
      "filter_spectacle": "ראווה גדולה",
      "filter_easy_english": "אנגלית קלה",
      "filter_must_see": "חובה לראות",
      "filter_hidden_gem": "פנינה נסתרת",
      "filter_tsufs_faves": "המועדפות של צוף",
      "filter_off_west_end": "אוף ווסט אנד",

      // Field Preferences
      "preference": {
        "darkness_level": {
          "positive": "טון אפל ואינטנסיבי יותר",
          "negative": "טון קליל ומרגש יותר"
        },
        "jukebox": {
          "positive": "שירים מוכרים (סגנון ג'וקבוקס)",
          "negative": "מוזיקה מקורית (פחות סגנון ג'וקבוקס)"
        },
        "music_familiarity": {
          "positive": "מוזיקה מוכרת וקלה להנאה",
          "negative": "מוזיקה חדשה ומקורית"
        },
        "spectacle_level": {
          "positive": "מופע ראווה גדול ווויזואלי",
          "negative": "מופע אינטימי יותר, מונע על ידי סיפור"
        },
        "comedy_score": {
          "positive": "קומדיה וצחוק",
          "negative": "טון רציני ומרגש יותר"
        },
        "family_score": {
          "positive": "מופע ידידותי למשפחה",
          "negative": "מופע ממוקד יותר למבוגרים"
        },
        "family_friendly": {
          "positive": "מופע ידידותי למשפחה",
          "negative": "מופע ממוקד יותר למבוגרים"
        },
        "beginner_friendly": {
          "positive": "קל למעקב למתחילים",
          "negative": "מתאים יותר לחובבי מחזות זמר מנוסים"
        },
        "emotional_intensity": {
          "positive": "השפעה רגשית חזקה",
          "negative": "חוויה רגשית קלילה יותר"
        },
        "tone_match": {
          "positive": "התאמה קרובה יותר לטון המועדף עליך",
          "negative": "טון שונה ממה שאתה מעדיף"
        },
        "energy_level": {
          "positive": "אנרגיה גבוהה",
          "negative": "קצב רגוע יותר"
        },
        "romance_score": {
          "positive": "רומנטיקה ומערכות יחסים",
          "negative": "פחות דגש על רומנטיקה"
        },
        "humor_level": {
          "positive": "קומדיה וצחוק",
          "negative": "טון רציני יותר"
        },
        "music_quality": {
          "positive": "מוזיקה בלתי נשכחת",
          "negative": "פחות דגש על איכות מוזיקלית"
        },
        "story_depth": {
          "positive": "סיפור חזק",
          "negative": "פחות דגש על עומק הסיפור"
        },
        "classic": {
          "positive": "מחזמר קלאסי",
          "negative": "מופע מודרני יותר"
        },
        "must_see": {
          "positive": "מופע חובה ופופולרי",
          "negative": "מופע פחות מיינסטרים"
        },
        "hidden_gem": {
          "positive": "משהו שונה וייחודי",
          "negative": "בחירה מיינסטרים יותר"
        }
      },

      // Comparisons
      "comparison": {
        "spectacle_level": {
          "0": "{{winner}} מספק יותר ראווה ויזואלית מאשר {{loser}}",
          "1": "{{loser}} אינטימי יותר בקנה מידה"
        },
        "humor_level": {
          "0": "{{winner}} מצחיק יותר מאשר {{loser}}",
          "1": "{{loser}} לוקח את עצמו יותר ברצינות"
        },
        "comedy_score": {
          "0": "{{winner}} נוטה יותר לקומדיה מאשר {{loser}}",
          "1": "{{loser}} כוללת פחות רגעים קומיים"
        },
        "emotional_intensity": {
          "high_vs_low": {
            "0": "ל-{{winner}} יש יותר עומק רגשי מאשר ל-{{loser}}",
            "1": "{{loser}} קליל יותר בטון"
          },
          "low_vs_high": {
            "0": "{{winner}} קליל יותר מאשר {{loser}}",
            "1": "{{loser}} כבד ואינטנסיבי יותר"
          }
        },
        "energy_level": {
          "0": "{{winner}} מתאים להעדפת האנרגיה שלך טוב יותר מאשר {{loser}}",
          "1": "ל-{{loser}} יש קצב שונה"
        },
        "beginner_friendly": {
          "0": "{{winner}} נגיש יותר למתחילים מאשר {{loser}}",
          "1": "{{loser}} מניח יותר ניסיון בתיאטרון"
        },
        "family_friendly": {
          "0": "{{winner}} מתאים יותר לילדים מאשר {{loser}}",
          "1": "{{loser}} פונה יותר למבוגרים"
        },
        "family_score": {
          "0": "{{winner}} עובד טוב יותר למשפחות מאשר {{loser}}",
          "1": "{{loser}} מיועד לקהל מבוגר יותר"
        },
        "jukebox": {
          "0": "{{winner}} כולל יותר שירים מוכרים מאשר {{loser}}",
          "1": "ל-{{loser}} יש יותר מוזיקה מקורית"
        },
        "music_familiarity": {
          "0": "{{winner}} קל יותר להנאה מוזיקלית מאשר {{loser}}",
          "1": "ל-{{loser}} יש מנגינות פחות מוכרות"
        },
        "classic": {
          "0": "{{winner}} מרגיש יותר כמו מחזמר קלאסי מאשר {{loser}}",
          "1": "{{loser}} מודרני יותר בסגנון"
        },
        "romance_score": {
          "0": "ל-{{winner}} יש יותר רומנטיקה מאשר ל-{{loser}}",
          "1": "{{loser}} מתמקד פחות במערכות יחסים"
        },
        "default": {
          "0": "{{winner}} חזק יותר בהעדפה זו",
          "1": "{{loser}} לא תואם באותה מידה"
        },

        // Reason fallbacks
        "date_mismatch": "המופע אינו מציג בתאריכים שלך.",
        "kids_mismatch": "{{winner}} מתאים יותר לילדים.",
        "duration_mismatch": "{{winner}} מתאים יותר להעדפתך למופע קצר יותר.",
        "english_mismatch": "{{winner}} קל יותר למעקב עם אנגלית מוגבלת.",
        "preference_match": "{{winner}} מתאים להעדפתך ל{{preference}} טוב יותר מאשר {{loser}}.",
        "overall_match": "{{winner}} הוא התאמה כללית חזקה יותר למה שאתה מחפש מאשר {{loser}}.",
        "strong_on": "חזק ב{{preference}}"
      },

      // Questions V2 & Dynamic Reasons
      "questions": {
        "q1_group": {
          "question_text": "עם מי אתם הולכים?",
          "answers": {
            "family_kids": "משפחה עם ילדים",
            "adults_and_teens": "מבוגרים ובני נוער",
            "adults": "מבוגרים בלבד"
          }
        },
        "q10_dates": {
          "question_text": "מתי תהיו בלונדון?",
          "answers": {
            "all_dates": "בכל התאריכים, אני גמיש/ה",
            "specific_dates": "תאריכים ספציפיים"
          }
        },
        "q9_experience": {
          "question_text": "כמה מחזות זמר ראיתם בעבר?",
          "answers": {
            "first_time": "זה יהיה המחזמר הראשון שלי",
            "a_few": "ראיתי כמה בודדים",
            "many": "ראיתי מלא!"
          }
        },
        "q2_english": {
          "question_text": "עד כמה אתם נוחים עם אנגלית?",
          "answers": {
            "native_or_fluent": "נוח מאוד / שוטף",
            "ok_but_not_perfect": "בסדר, לא מושלם",
            "basic": "אנגלית בסיסית"
          }
        },
        "q3_mood": {
          "question_text": "במה אתם במצב רוח?",
          "answers": {
            "laugh": "אני רוצה לצחוק",
            "feel_good": "נעים ומרומם",
            "epic_emotional": "לראות משהו אפי ולהתרגש",
            "dark_intense": "אני בצד האפל והאינטנסיבי"
          }
        },
        "q4_focus": {
          "question_text": "מה חשוב לכם יותר?",
          "answers": {
            "big_spectacle": "ראווה גדולה",
            "strong_story": "סיפור חזק",
            "no_preference": "אין לי העדפה"
          }
        },
        "q5_music": {
          "question_text": "איזה סוג מוזיקה אתם מעדיפים?",
          "answers": {
            "famous_songs": "שירים שאני מכיר/ה",
            "original_music": "מוזיקה מקורית חדשה",
            "no_preference": "אין לי העדפה"
          }
        },
        "q7_length": {
          "question_text": "כמה זמן אתם רוצים שתהיה ההצגה?",
          "answers": {
            "short": "לא יותר מדי ארוכה",
            "dont_care": "לא אכפת לי"
          }
        },
        "q11_seen_before": { "question_text": "איזה ממחזות הזמר האלו כבר ראיתם ואהבתם?" },
        "q_priority_rank": {
          "question_text": "מה הכי חשוב לכם במחזמר?",
          "answers": {
            "easy_english": "אנגלית קלה",
            "strong_story": "סיפור חזק ומרגש",
            "funny": "מצחיק / קורע מצחוק",
            "grand_spectacle": "שואו גדול / ויזואליות מרשימה",
            "songs_i_know": "שירים שאני מכיר/ה (Jukebox)",
            "not_too_long": "לא ארוך מדי",
            "hidden_gem": "משהו מיוחד / פנינה נסתרת"
          }
        }
      },
      "tag_map": {
        "Adaptation": "עיבוד",
        "Adult Humor": "הומור למבוגרים",
        "Adult Themes": "תכנים למבוגרים",
        "Adventure": "הרפתקה",
        "Anthology": "אנתולוגיה",
        "Artistic": "אמנותי",
        "Atmospheric": "אטמוספרי",
        "Award-Winning": "זוכה פרסים",
        "Based on Movie": "מבוסס על סרט",
        "Beginner Friendly": "מתאים למתחילים",
        "Big Ensemble": "אנסמבל גדול",
        "Big Laughter": "צחוקים גדולים",
        "Big Songs": "שירים גדולים",
        "Big Vocals": "קולות עוצמתיים",
        "Bold Humor": "הומור נועז",
        "British Charm": "קסם בריטי",
        "British Comedy": "קומדיה בריטית",
        "Camp": "קאמפ",
        "Character-Driven": "מונע דמויות",
        "Classic": "קלאסיקה",
        "Classic Broadway": "קלאסיקת ברודווי",
        "Classic Musical": "מחזמר קלאסי",
        "Classic Story": "סיפור קלאסי",
        "Classical/rock fusion": "פיוז'ן קלאסי/רוק",
        "Clever": "חכם",
        "Clever Humor": "הומור חכם",
        "Cole Porter": "קול פורטר",
        "College/law school": "קולג'/בית ספר למשפטים",
        "Comedy": "קומדיה",
        "Comedy-drama": "קומדיה-דרמה",
        "Coming-of-age": "סיפור התבגרות",
        "Critically Acclaimed": "שבחי המבקרים",
        "Crowd Pleaser": "כולם אוהבים",
        "Cult Favorite": "פולחן מאוהדים",
        "Cultural Phenomenon": "תופעה תרבותית",
        "Dance Heavy": "ריקוד אינטנסיבי",
        "Dance-heavy": "ריקוד אינטנסיבי",
        "Dark": "אפל",
        "Dark / Light Mix": "שילוב אפל/קליל",
        "Dark / Serious": "אפל / רציני",
        "Dark Romance": "רומנטיקה אפלה",
        "Dark humor": "הומור אפל",
        "Disney": "דיסני",
        "Disney Musical": "מחזמר דיסני",
        "Drama": "דרמה",
        "Dramatic": "דרמטי",
        "Easy English": "אנגלית קלה",
        "Edgy": "חסר מורא",
        "Emotional": "מרגש",
        "Emotional Moments": "רגעים מרגשים",
        "Empowering": "מעצים",
        "Empowerment": "העצמה",
        "Ensemble": "אנסמבל",
        "Epic": "אפי",
        "Fairytale": "אגדת פיות",
        "Family": "משפחה",
        "Family Friendly": "ידידותי למשפחה",
        "Famous Songs": "שירים מפורסמים",
        "Fan Favorite": "אהוב המעריצים",
        "Fantasy": "פנטזיה",
        "Fashion": "אופנה",
        "Fast-Paced": "קצב מהיר",
        "Feel-Good": "מרגיש טוב",
        "Feel-Good Chaos": "כאוס שמח",
        "Feminist": "פמיניסטי",
        "Folk/Jazz Feel": "פולק/ג'אז",
        "Friendship": "חברות",
        "Fun": "כיף",
        "Fun Concept": "קונספט כיפי",
        "Fun Tone": "אווירה כיפית",
        "Funny": "מצחיק",
        "Futuristic": "עתידני",
        "Gentle Humor": "הומור עדין",
        "Ghosts": "רוחות",
        "Girl Power": "גרל פאוור",
        "Glamorous": "גלמורטי",
        "Grand Staging": "הפקה מרהיבה",
        "Heartwarming": "מחמם לב",
        "High Energy": "אנרגיה גבוהה",
        "Hip-Hop Musical": "מחזמר היפ-הופ",
        "Historic": "היסטורי",
        "Historic London": "לונדון היסטורית",
        "Holiday Vibes": "ווייב של חגים",
        "Hope": "תקווה",
        "Hopeful": "מלא תקווה",
        "Iconic": "אייקוני",
        "Iconic Show": "הצגה אייקונית",
        "Iconic Songs": "שירים אייקוניים",
        "Iconic Theatre": "תיאטרון אייקוני",
        "Inclusive": "כוללני",
        "Inspirational": "מעורר השראה",
        "Intimate": "אינטימי",
        "Irreverent": "חסר מורא",
        "Jazz Age": "עידן הג'אז",
        "Journey": "מסע",
        "Jukebox Musical": "מחזמר ג'וקבוקס",
        "Kids Cast": "שחקנים ילדים",
        "Kids Friendly": "מתאים לילדים",
        "Kids Love It": "ילדים אוהבים",
        "Kids Musical": "מחזמר ילדים",
        "LGBTQ+": "LGBTQ+",
        "LGBTQ+ Vibes": "וייבס LGBTQ+",
        "Legendary Musical": "מחזמר אגדי",
        "Life Reflection": "הרהורים על החיים",
        "Long Running": "הצגה ותיקה",
        "Love Triangle": "משולש אהבה",
        "Lyrical": "לירי",
        "Mature Themes": "תכנים בשלים",
        "Modern": "מודרני",
        "Modern Musical": "מחזמר מודרני",
        "Musical": "מחזמר",
        "Mythology": "מיתולוגיה",
        "Non-Native Friendly": "מתאים לדוברי אנגלית כשפה שנייה",
        "Nostalgia": "נוסטלגיה",
        "Not Serious": "לא רציני",
        "Parody": "פרודיה",
        "Party Atmosphere": "אווירת מסיבה",
        "Passion story": "סיפור תשוקה",
        "Political": "פוליטי",
        "Pop Concert Style": "סגנון קונצרט פופ",
        "Pop Music": "מוזיקת פופ",
        "Pop Music Style": "סגנון מוזיקת פופ",
        "Pop Musical": "מחזמר פופ",
        "Pop Songs": "שירי פופ",
        "Powerful": "עוצמתי",
        "Powerful Performances": "הופעות עוצמתיות",
        "Queer": "קווירי",
        "Quirky": "ייחודי ומוזר",
        "Religious": "דתי",
        "Resilience": "חוסן",
        "Rock opera": "אופרת רוק",
        "Rock score": "פרטיטורת רוק",
        "Roller-Skating Musical": "מחזמר גלגיליות",
        "Romance": "רומנטיקה",
        "Romantic": "רומנטי",
        "Romantic Comedy": "קומדיה רומנטית",
        "Satire": "סאטירה",
        "Satirical": "סאטירי",
        "Shocking but Hilarious": "מזעזע אבל מצחיק",
        "Short Show": "הצגה קצרה",
        "Silly Fun": "כיף מטופש",
        "Smart Humor": "הומור חכם",
        "Story Driven": "מונע סיפור",
        "Story-Driven": "מונע סיפור",
        "Stylish": "סטיילי",
        "Sweet": "מתוק",
        "Teen Friendly": "מתאים לנוער",
        "Theatre Lovers Favorite": "אהוב חובבי תיאטרון",
        "Time/aging themes": "נושאי זמן והזדקנות",
        "Tourist Favorite": "אהוב תיירים",
        "True story": "סיפור אמיתי",
        "Unique Experience": "חוויה ייחודית",
        "Unique Style": "סגנון ייחודי",
        "Uplifting": "מרומם",
        "Very Funny": "מצחיק מאוד",
        "Villain Origin Story": "סיפור מקור של נבל",
        "Visual Spectacle": "ראווה ויזואלית",
        "War & Revolution": "מלחמה ומהפכה",
        "Wartime Story": "סיפור תקופת מלחמה",
        "Wholesome": "תמים ובריא",
        "Witty": "חכם ומשעשע",
        "Workplace Drama": "דרמה במקום עבודה"
      },

      "reasons": {
        "Suitable for kids": "מתאים לילדים",
        "Avoid dark themes for kids": "המנעות מתכנים אפלים (מותאם לילדים)",
        "Funny for families": "מצחיק ומתאים למשפחות",
        "Visual and engaging for kids": "ויזואלי ומרתק לילדים",
        "Less focus on very family-oriented shows": "פחות ממוקד במשפחות",
        "Slightly downrank very family/kid-focused shows": "פחות מותאם לילדים",
        "Easy to enjoy for first-timers": "קל להנאה למתחילים",
        "Great first musical experience": "חוויה מעולה למחזמר ראשון",
        "A strong classic can be perfect": "קלאסיקה על-זמנית",
        "You’ll enjoy something new and different": "תיהנו ממשהו חדש ושונה",
        "You’ve probably seen big classics": "כנראה כבר ראיתם את הקלאסיקות הגדולות",
        "Show starts on or before end of visit": "המופע מתחיל בזמן הביקור",
        "Show is still running during visit": "המופע מציג בזמן הביקור",
        "Easier English": "אנגלית קלה",
        "Less dialogue-heavy": "פחות עמוס בטקסט",
        "Story-forward / text-driven": "מונע על ידי סיפור / טקסט",
        "Emotional story": "סיפור מרגש",
        "Very funny": "מצחיק מאוד",
        "Big visual wow factor": "וואו ויזואלי גדול",
        "Jukebox / famous songs": "שירי ג'וקבוקס מוכרים",
        "Familiar music": "מוזיקה מוכרת",
        "Shorter runtime": "זמן ריצה קצר יותר",
        "Hidden gem": "פנינה נסתרת",
        "Off West End": "אוף-ווסט אנד"
      }
    }
  }
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'en',
    load: 'languageOnly',   // normalises 'en-US' → 'en', 'he-IL' → 'he'
    debug: false,
    interpolation: {
      escapeValue: false,
    },
    react: {
      useSuspense: false
    }
  });

export default i18n;
